#!/usr/bin/env python3
"""Build the SCR-LIP pilot registry from curated claims.
Empirical claims (Amato's published studies + external evidence) go into claims.json.
The IIT2/gfWAT theory claims are HELD OUT (per author) in _held_out_theory.json.
Also emits claims.csv (flattened) for spreadsheet review.
"""
import json, csv, os

DIR = os.path.dirname(os.path.abspath(__file__))
COMMON = {"curators": [{"name": "Alexandre C. M. Amato", "orcid": "0000-0003-4008-4029", "role": "lead_curator"}],
          "created": "2026-05-30", "updated": "2026-05-30", "license": "CC-BY-4.0", "registry_version": "0.1"}

def C(statement, statement_pt, claim_type, context, ks, ec, evidence, relations, gaps, src):
    return {"statement": statement, "statement_pt": statement_pt, "claim_type": claim_type,
            "context": context, "knowledge_state": ks, "evidence_confidence": ec,
            "evidence": evidence, "relations": relations, "gaps": gaps, "primary_amato_source": src}

def ev(ref, stance, design, n, rob, year, amato, note=""):
    return {"ref": ref, "stance": stance, "study_design": design, "n": n, "risk_of_bias": rob,
            "year": year, "amato_authored": amato, "note": note}

def ctx(pop, exp, comp, out, scope):
    return {"population": pop, "condition": "lipedema", "exposure": exp, "comparator": comp, "outcome": out, "scope": scope}

# ---------------- REGISTRY (empirical) ----------------
claims = [
 # --- Definition & clinical features ---
 C("Lipedema is a distinct clinical entity separate from obesity and lymphedema, characterized by bilateral, symmetrical, painful subcutaneous fat accumulation of the lower limbs that spares the feet, although all three can coexist.",
   "O lipedema é uma entidade clínica distinta da obesidade e do linfedema, caracterizada por acúmulo subcutâneo doloroso, bilateral e simétrico em membros inferiores que poupa os pés, embora as três condições possam coexistir.",
   "definitional", ctx("adults, predominantly women","","obesity and lymphedema","distinction as a separate disease entity","disease definition / differential diagnosis"),
   "established","moderate",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"Brazilian Delphi consensus (expert agreement, not primary evidence)"),
    ev("amato_2020_lipedema-unique-entity.pdf","supporting","expert_opinion",None,"high",2020,True,"narrative review")],
   [{"type":"contextualizes","target_hint":"lymphedema"},{"type":"contextualizes","target_hint":"obesity"}],
   "No objective gold-standard diagnostic test; rests on clinical criteria and expert consensus.","DOI:10.1590/1677-5449.202301832"),
 C("Clinical signs that help diagnose lipedema and distinguish it from lymphedema include a usually negative Kaposi-Stemmer sign, the cuff sign with foot sparing, fat painful on palpation, easy bruising, and minimal pitting edema (Stemmer becomes positive only when secondary lymphedema/lipolymphedema develops).",
   "Sinais clínicos que auxiliam o diagnóstico do lipedema e o distinguem do linfedema incluem sinal de Kaposi-Stemmer geralmente negativo, sinal do manguito com preservação dos pés, gordura dolorosa à palpação, equimoses fáceis e edema pouco depressível (Stemmer torna-se positivo apenas no lipolinfedema).",
   "diagnostic", ctx("patients with lipedema","clinical examination signs","lymphedema","clinical differentiation","diagnostic criteria"),
   "probable","moderate",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus on Stemmer, pain, bruising, pitting"),
    ev("Amato_2019_Lipedema_obesidade_linfedema_insuficiencia_venosa.pdf","supporting","case_report",1,"high",2019,True,"comparative table")],
   [{"type":"contextualizes","target_hint":"lymphedema differential"},{"type":"co_occurs","target_hint":"lipolymphedema"}],
   "Signs lack validated sensitivity/specificity; diagnosis remains clinical and operator-dependent.","DOI:10.1590/1677-5449.202301832"),
 C("In the Brazilian Delphi consensus, experts agreed that lipedema and obesity do not have a causal relationship and that BMI is of limited value in differentiating lipedema from obesity.",
   "No consenso Delphi brasileiro, os especialistas concordaram que lipedema e obesidade não têm relação causal e que o IMC tem valor limitado para diferenciá-los.",
   "definitional", ctx("Brazilian lipedema specialists (Delphi)","obesity","obesity","absence of causal link; limited BMI utility","pathophysiology/diagnosis"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"expert agreement (level C), not demonstrated causation")],
   [{"type":"contextualizes","target_hint":"obesity"}],
   "Expert-consensus position with low self-rated evidence; obesity is a common comorbidity blurring the boundary.","DOI:10.1590/1677-5449.202301832"),
 C("Lipedema is a multifactorial disorder whose symptoms are closely linked to female hormonal transitions (puberty, pregnancy, menopause) and to chronic low-grade inflammation, on a polygenic predisposition.",
   "O lipedema é um distúrbio multifatorial cujos sintomas estão ligados às transições hormonais femininas (puberdade, gestação, menopausa) e à inflamação crônica de baixo grau, sobre predisposição poligênica.",
   "causal", ctx("predominantly women with lipedema","hormonal transitions + low-grade inflammation; polygenic","","symptom variation, fat deposition, progression","etiology (general, multifactorial)"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus: hormones trigger/exacerbate (4.46); inflammation contributes (4.25)"),
    ev("amato_2020_lipedema-unique-entity.pdf","supporting","expert_opinion",None,"high",2020,True,"")],
   [{"type":"associates","target_hint":"hormonal/estrogen"},{"type":"associates","target_hint":"polygenic inheritance"},{"type":"causes","target_hint":"low-grade inflammation"}],
   "Specific genes/mediators hypothesized rather than demonstrated in controlled studies.","amato_2020_lipedema-unique-entity.pdf"),
 # --- Diagnosis / imaging ---
 C("In women undergoing venous ultrasound, dermal/subcutaneous thickness measurements at the pre-tibial region, anterior thigh and lateral leg can distinguish clinically diagnosed lipedema from non-lipedema in the lower limbs.",
   "Em mulheres submetidas a ultrassom venoso, medidas de espessura dérmica/subcutânea na região pré-tibial, coxa anterior e perna lateral distinguem lipedema clinicamente diagnosticado de não-lipedema nos membros inferiores.",
   "diagnostic", ctx("adult women undergoing venous ultrasound","ultrasound thickness measurement","clinical diagnosis (reference)","discrimination lipedema vs non-lipedema","lower limbs, single-center Brazil"),
   "emerging","low",
   [ev("DOI:10.1177/02683555211002340","supporting","cross_sectional",89,"moderate",2021,True,"two blinded examiners; ROC cutoffs; pre-tibial best discriminator")],
   [{"type":"diagnoses","target_hint":"ultrasound diagnosis"}],
   "Single-center convenience sample; cutoffs not externally validated.","DOI:10.1177/02683555211002340"),
 C("For ultrasound diagnosis of lower-limb lipedema, subcutaneous thickness cutoffs of >11.7 mm (pre-tibial), >17.9 mm (anterior thigh), >8.4 mm (lateral leg) and >7.0 mm (medial supramalleolar) provide reproducible reference values.",
   "Para o diagnóstico ultrassonográfico do lipedema, cortes de espessura subcutânea de >11,7 mm (pré-tibial), >17,9 mm (coxa anterior), >8,4 mm (perna lateral) e >7,0 mm (supramaleolar medial) fornecem valores de referência reprodutíveis.",
   "diagnostic", ctx("adult women evaluated for lipedema","high-frequency ultrasound","clinically diagnosed lipedema","reference cutoff values","lower limbs, four points"),
   "emerging","low",
   [ev("DOI:10.1177/02683555211002340","supporting","cross_sectional",89,"moderate",2021,True,"Youden/ROC cutoffs; later reused by Vargas 2025 and Foureaux 2025")],
   [{"type":"diagnoses","target_hint":"ultrasound cutoffs"}],
   "Derived from a single Brazilian cohort; no prospective multicenter validation.","DOI:10.1177/02683555211002340"),
 C("Because obesity is commonly defined by BMI alone (which disregards fat distribution), lipedema is frequently underdiagnosed when workup stops at an established obesity diagnosis; ~81% of lipedema patients are classified overweight/obese by BMI.",
   "Como a obesidade é definida apenas pelo IMC (que ignora a distribuição de gordura), o lipedema é frequentemente subdiagnosticado quando a investigação para num diagnóstico de obesidade; ~81% das pacientes com lipedema são classificadas como sobrepeso/obesas pelo IMC.",
   "clinical_association", ctx("women evaluated for limb fat/obesity","BMI-only obesity classification","fat-distribution-aware assessment","underdiagnosis of lipedema","diagnostic reasoning"),
   "probable","low",
   [ev("DOI:10.1177/02683555211002340","supporting","cross_sectional",89,"moderate",2021,True,"81% of lipedema group overweight/obese by BMI alone"),
    ev("Amato_2021_Sobrediagnostico.pdf","supporting","expert_opinion",None,"high",2022,True,"book chapter on overdiagnosis")],
   [{"type":"associates","target_hint":"obesity vs lipedema diagnosis"}],
   "Supported by expert reasoning and observational frequency; no quantified missed-diagnosis rate.","Amato_2021_Sobrediagnostico.pdf"),
 C("A self-administered lipedema screening questionnaire achieves a high probability of correct classification (~91%) between women with and without lipedema, supporting its use to raise clinical suspicion.",
   "Um questionário de rastreamento de lipedema autoaplicável alcança alta probabilidade de classificação correta (~91%) entre mulheres com e sem lipedema, apoiando seu uso para elevar a suspeição clínica.",
   "diagnostic", ctx("women with and without lipedema at a vascular clinic","self-administered screening questionnaire","prior clinical diagnosis","probability of correct classification","screening tool development, Brazil"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.200114","supporting","validation",109,"moderate",2020,True,"per-question model 91.2% correct classification; AUC 0.86")],
   [{"type":"diagnoses","target_hint":"screening questionnaire"}],
   "Small convenience sample at a specialized clinic; reference standard clinical only.","DOI:10.1590/1677-5449.200114"),
 C("The Brazilian Portuguese lipedema symptoms questionnaire (QuASiL) was translated, culturally adapted and validated, showing high comprehension and symptom-intensity scores that correlate with limb volume by segmental bioimpedance.",
   "O questionário brasileiro de sintomas do lipedema (QuASiL) foi traduzido, adaptado e validado, com alta compreensão e escores de intensidade que se correlacionam com o volume dos membros por bioimpedância segmentar.",
   "definitional", ctx("Brazilian women with and without lipedema","QuASiL questionnaire","segmental bioimpedance volume","comprehension and symptom-volume correlation","instrument validation"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.200049","supporting","validation",154,"moderate",2020,True,"96.4% comprehension; symptom intensity correlated with limb volume")],
   [{"type":"contextualizes","target_hint":"symptom assessment instrument"}],
   "Validated as a symptoms scale, not a diagnostic criterion.","DOI:10.1590/1677-5449.200049"),
 C("Qualitative ultrasound patterns of the dermis and hypodermis (Lipedema Dermal and Hypodermal Classification, LDHC) describe structural changes (septal alteration, echogenic nodules, dermal-hypodermal junction disruption) that may correspond to stages of inflammation and fibrosis.",
   "Padrões ultrassonográficos qualitativos da derme e hipoderme (Classificação Dérmica e Hipodérmica do Lipedema, LDHC) descrevem alterações estruturais que podem corresponder a estágios de inflamação e fibrose.",
   "diagnostic", ctx("women with clinically diagnosed lipedema, obesity excluded","high-frequency ultrasound (qualitative)","normal/obese architecture","morphologic classification","single-center retrospective imaging"),
   "emerging","low",
   [ev("DOI:10.4236/jbise.2025.184008","supporting","case_series",34,"high",2025,True,"Vargas et al.; obese non-lipedema show preserved layered septa")],
   [{"type":"diagnoses","target_hint":"qualitative ultrasound classification"}],
   "Retrospective; no interobserver validation or clinical-stage correlation.","DOI:10.4236/jbise.2025.184008"),
 C("Echogenic (hyperechoic) subcutaneous nodules in lipedema can be subclassified into at least four morphological variants (LDHC 3a-3d) whose distribution corresponds most strongly to the patient's most painful site.",
   "Os nódulos subcutâneos ecogênicos do lipedema podem ser subclassificados em pelo menos quatro variantes (LDHC 3a-3d), cuja distribuição se associa mais fortemente ao ponto de maior dor.",
   "diagnostic", ctx("lipedema patients classified LDHC 3, obesity excluded","ultrasound nodule morphology","","nodule subclassification and pain correlation","single-center, two radiologists"),
   "speculative","very_low",
   [ev("DOI:10.4236/jbise.2025.1810029","supporting","case_series",20,"high",2025,True,"Foureaux et al.; 62 nodules; distribution tied to most painful site, not BMI/age")],
   [{"type":"diagnoses","target_hint":"echogenic nodule subclassification"},{"type":"associates","target_hint":"pain"}],
   "Small descriptive series; no histopathologic confirmation of subtypes.","DOI:10.4236/jbise.2025.1810029"),
 # --- Prevalence & epidemiology ---
 C("The estimated prevalence of probable lipedema among adult Brazilian women is approximately 12.3%, indicating a common rather than rare condition.",
   "A prevalência estimada de lipedema provável entre mulheres adultas brasileiras é de aproximadamente 12,3%, indicando condição comum, não rara.",
   "epidemiologic", ctx("adult Brazilian women","","","prevalence of probable lipedema (~12.3%)","epidemiology, questionnaire screening"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.202101981","supporting","cross_sectional",253,"moderate",2022,True,"online validated screening questionnaire; selection bias"),
    ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus endorsed 12.3% (lowest-agreement statement)")],
   [{"type":"contextualizes","target_hint":"global prevalence estimates"}],
   "Screening-based, not clinically confirmed; self-report/selection bias; may overstate true prevalence.","DOI:10.1590/1677-5449.202101981"),
 C("Because ~49% of women have varicose veins and ~11% have lipedema, a substantial proportion of women undergoing venous ultrasound for varicose veins also have coexisting lipedema, making the venous exam an opportunity for lipedema screening.",
   "Como ~49% das mulheres têm varizes e ~11% têm lipedema, parcela substancial das mulheres em ultrassom venoso por varizes também tem lipedema concomitante, tornando o exame venoso uma oportunidade de rastreamento.",
   "epidemiologic", ctx("women with varicose veins undergoing venous ultrasound","varicose veins/venous insufficiency","general female population","coexistence of lipedema","vascular clinic, screening opportunity"),
   "emerging","low",
   [ev("DOI:10.1177/02683555211002340","supporting","cross_sectional",89,"moderate",2021,True,"45.1% of lipedema patients had varicose veins")],
   [{"type":"associates","target_hint":"varicose veins coexistence"}],
   "Coexistence frequencies partly from external literature; vascular-clinic selection bias.","DOI:10.1177/02683555211002340"),
 C("Lipedema occurs in men with the classical phenotype (bilateral, symmetrical, foot-sparing lower-limb fat accumulation, negative Stemmer sign), although it almost exclusively affects women and male occurrence is rare.",
   "O lipedema ocorre em homens com o fenótipo clássico (acúmulo bilateral, simétrico, poupando os pés, Stemmer negativo), embora afete quase exclusivamente mulheres e a ocorrência masculina seja rara.",
   "clinical_association", ctx("men diagnosed with lipedema at a referral center","male sex","classical female presentation","classical phenotype in men","lipedema in men"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.87332","supporting","case_series",5,"high",2025,True,"5 men 31-58y; classical phenotype; no histopathology"),
    ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"'occurrence in men is rare' (4.23)")],
   [{"type":"contextualizes","target_hint":"male lipedema / sex distribution"}],
   "Small retrospective series without histopathology; true male prevalence uncertain.","DOI:10.7759/cureus.87332"),
 # --- Comorbidities ---
 C("Women meeting lipedema screening criteria have a higher prevalence of positive ADHD self-report (ASRS-18) than women without lipedema (76.9% vs 54%; RR 1.424).",
   "Mulheres que atendem aos critérios de triagem para lipedema têm maior prevalência de autorrelato positivo de TDAH (ASRS-18) do que mulheres sem lipedema (76,9% vs 54%; RR 1,424).",
   "clinical_association", ctx("adult Brazilian women (online, n=354)","lipedema screening positivity","women without lipedema criteria","ADHD symptoms (ASRS-18 positive)","screening-based prevalence"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.35570","supporting","cross_sectional",354,"moderate",2023,True,"RR 1.424 (95%CI 1.22-1.66), p<0.0001; self-report screening")],
   [{"type":"associates","target_hint":"ADHD"}],
   "Self-reported screening, convenience sampling, no confounder adjustment, single study.","DOI:10.7759/cureus.35570"),
 C("Higher lipedema screening scores correlate positively with higher ADHD (ASRS-18) scores, supporting a dimensional co-occurrence of the two conditions.",
   "Escores mais altos de triagem para lipedema correlacionam-se positivamente com escores mais altos de TDAH (ASRS-18), sustentando coocorrência dimensional.",
   "clinical_association", ctx("adult Brazilian women (n=354)","lipedema screening score","lower lipedema score","ADHD symptom score","correlation of continuous scores"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.35570","supporting","cross_sectional",354,"moderate",2023,True,"Pearson correlation p<0.001")],
   [{"type":"co_occurs","target_hint":"ADHD"}],
   "Correlation does not establish causation; questionnaire-based, single cross-sectional sample.","DOI:10.7759/cureus.35570"),
 C("Joint hypermobility (Hypermobility Spectrum Disorder) is a frequent comorbidity of lipedema, present in approximately 44% of adult patients in a cross-sectional cohort.",
   "A hipermobilidade articular (Transtorno do Espectro de Hipermobilidade) é comorbidade frequente do lipedema, presente em ~44% das adultas em coorte transversal.",
   "clinical_association", ctx("women with lipedema (cross-sectional cohort)","lipedema","lymphedema patients / general population","joint hypermobility (HSD)","comorbidity prevalence"),
   "emerging","moderate",
   [ev("DOI:10.3390/jcm14207195","supporting","cross_sectional",716,"moderate",2025,False,"Fiengo & Sbarbati; 44% hypermobile (60% in childhood); n=670 lipedema")],
   [{"type":"co_occurs","target_hint":"joint hypermobility / hEDS"}],
   "Single-center cross-sectional; hypermobility cutoffs vary; not Amato-authored.","DOI:10.3390/jcm14207195"),
 C("Secondary lymphedema (lipolymphedema) can develop as a complication of advanced lipedema due to chronic lymphatic overload, with lymph stasis becoming more evident at advanced disease stages.",
   "O linfedema secundário (lipolinfedema) pode surgir como complicação do lipedema avançado por sobrecarga linfática crônica, com a estase linfática tornando-se mais evidente nos estágios avançados.",
   "clinical_association", ctx("patients with advanced lipedema","advanced/chronic lipedema","early-stage lipedema","secondary lymphedema (lipolymphedema) / lymph stasis","disease progression (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus: lipolymphedema as a complication 3.95 (level B); lymph stasis more evident in advanced stages 4.36")],
   [{"type":"co_occurs","target_hint":"lymphedema / lipolymphedema"}],
   "Lymphatic dysfunction in early lipedema is debated; statement is consensus-level (level B/C), not from longitudinal imaging.","DOI:10.1590/1677-5449.202301832"),
 C("Increased limb adipose tissue in lipedema can impair mobility and hinder activities of daily living, contributing to functional disability beyond the cosmetic burden.",
   "O aumento do tecido adiposo dos membros no lipedema pode prejudicar a mobilidade e dificultar atividades da vida diária, contribuindo para incapacidade funcional além do impacto estético.",
   "clinical_association", ctx("patients with lipedema (especially advanced stages)","increased limb adiposity","","impaired mobility / limitation of activities of daily living","functional impact (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus: increased adipose tissue hinders activities of daily living 4.55, level C")],
   [{"type":"associates","target_hint":"functional disability / mobility"}],
   "Functional impact endorsed by expert consensus; not quantified here with standardized disability instruments.","DOI:10.1590/1677-5449.202301832"),
 C("Thyroid disorders may be more frequent in lipedema than in lymphedema, with a cross-sectional cohort reporting thyroid disease in 24.4% of lipedema vs 14.89% of lymphedema patients.",
   "Distúrbios tireoidianos podem ser mais frequentes no lipedema que no linfedema, com coorte transversal relatando doença tireoidiana em 24,4% (lipedema) vs 14,89% (linfedema).",
   "epidemiologic", ctx("women with lipedema vs lymphedema (cross-sectional)","lipedema","lymphedema patients","thyroid disorder prevalence","comparative prevalence, single cohort"),
   "emerging","low",
   [ev("DOI:10.3390/jcm14207195","supporting","cross_sectional",716,"moderate",2025,False,"Fiengo & Sbarbati; 24.4% vs 14.89%")],
   [{"type":"associates","target_hint":"thyroid disease"}],
   "Thyroid disorder not Hashimoto-specific; single cohort, no age/BMI adjustment; not Amato-authored.","DOI:10.3390/jcm14207195"),
 C("Lipedema and fibromyalgia frequently co-occur: a cross-sectional study found lipedema in 50% of women meeting ACR fibromyalgia criteria, with longer fibromyalgia diagnostic delay and younger menarche as risk factors.",
   "Lipedema e fibromialgia coocorrem com frequência: estudo transversal encontrou lipedema em 50% das mulheres com critérios ACR de fibromialgia, com maior tempo até o diagnóstico e menarca precoce como fatores de risco.",
   "clinical_association", ctx("adult women with fibromyalgia (ACR 2016, n=100)","fibromyalgia","fibromyalgia patients without lipedema","lipedema prevalence and risk factors","prevalence within a fibromyalgia population"),
   "emerging","low",
   [ev("DOI:10.1177/02683555251321042","supporting","cross_sectional",100,"moderate",2025,False,"Gunaydin; lipedema in 50%; pain correlated with widespread pain r=0.62")],
   [{"type":"co_occurs","target_hint":"fibromyalgia"}],
   "Single-center, no non-FM control; directionality unclear; not Amato-authored.","DOI:10.1177/02683555251321042"),
 C("Knee pain is a common musculoskeletal feature of lipedema, reported by 58.1% of women screening positive for lipedema in a Brazilian population study.",
   "A dor no joelho é característica musculoesquelética comum do lipedema, relatada por 58,1% das mulheres com triagem positiva em estudo populacional brasileiro.",
   "clinical_association", ctx("Brazilian women screening positive for lipedema","lipedema","","self-reported knee pain","musculoskeletal symptom prevalence"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.202101981","supporting","cross_sectional",253,"moderate",2022,True,"58.1% knee pain in screen-positive women")],
   [{"type":"associates","target_hint":"knee/patellofemoral pain"}],
   "Self-reported via screening questionnaire; no imaging confirmation; no BMI-matched comparator.","DOI:10.1590/1677-5449.202101981"),
 # --- Systemic associations: HLA / IgG / celiac / cancer (empirical only) ---
 C("Women with clinically diagnosed lipedema show a higher prevalence of the celiac-associated HLA-DQ2/DQ8 haplotypes than the general population (any HLA 61.1% vs 53.7%; both haplotypes 7.4% vs 1.2%).",
   "Mulheres com lipedema clinicamente diagnosticado apresentam maior prevalência dos haplótipos HLA-DQ2/DQ8 associados à celíaca do que a população geral (qualquer HLA 61,1% vs 53,7%; ambos 7,4% vs 1,2%).",
   "clinical_association", ctx("adult women with lipedema (Brazil), celiac excluded","lipedema phenotype","general/reference population HLA prevalence","HLA-DQ2/DQ8 carrier prevalence","single-center cohort, n=95"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.41594","supporting","cross_sectional",95,"high",2023,True,"convenience sample; historical comparator (Cecilio 2015)"),
    ev("DOI:10.1590/S0102-67202015000300009","supporting","cross_sectional",80,"moderate",2015,False,"general-population HLA comparator")],
   [{"type":"associates","target_hint":"HLA-DQ2/DQ8 susceptibility"}],
   "No concurrent control; selection bias toward symptomatic patients; cannot establish causation.","DOI:10.7759/cureus.41594"),
 C("In women with lipedema, food-specific IgG testing shows a paradox: a slightly higher number of positive food reactions despite markedly lower total IgG (1747 vs 2975 AU; p<0.001).",
   "Em mulheres com lipedema, o teste de IgG alimentar mostra paradoxo: número discretamente maior de reações positivas apesar de IgG total marcadamente menor (1747 vs 2975 UA; p<0,001).",
   "clinical_association", ctx("adult women with vs without lipedema (Brazil)","lipedema phenotype","women without lipedema","food-specific IgG positivity and total IgG","retrospective cross-sectional"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.93788","supporting","cross_sectional",234,"high",2025,True,"higher positive count NS (p=0.186); lower total IgG highly significant")],
   [{"type":"associates","target_hint":"mucosal/humoral immune dysregulation"}],
   "IgG subclasses not measured; possible diet/elimination confounding; food-IgG clinical meaning controversial.","DOI:10.7759/cureus.93788"),
 C("In a nationally representative NHANES sample, women with serologically confirmed celiac disease had significantly lower gynoid percent fat than non-celiac women (39.5% vs 42.6%; -7.4%; p=0.0007).",
   "Em amostra nacionalmente representativa (NHANES), mulheres com doença celíaca confirmada tiveram percentual de gordura ginoide significativamente menor que não celíacas (39,5% vs 42,6%; -7,4%; p=0,0007).",
   "clinical_association", ctx("US women >=20y (NHANES 2011-2014)","celiac disease autoimmunity","non-celiac women","gynoid percent fat (DXA)","cross-sectional, n=3833 (11 celiac)"),
   "emerging","low",
   [ev("DOI:10.64898/2025.12.01.25341350","supporting","cross_sectional",3833,"moderate",2025,True,"only 11 celiac cases; ethnic imbalance; cross-sectional"),
    ev("DOI:10.7759/cureus.104222","supporting","cross_sectional",3833,"moderate",2026,True,"peer-reviewed version, same dataset")],
   [{"type":"associates","target_hint":"celiac vs gynoid adiposity"}],
   "Reverse causation partly addressed by BMI strata; n=11 precludes adjustment; DXA proxy not validated against clinical lipedema.","DOI:10.64898/2025.12.01.25341350"),
 C("The reduced gynoid adiposity associated with celiac disease in NHANES persisted among overweight/obese women (-8.7% overall, p=0.005; -11.3% in obese, p=0.039), arguing against leanness/malnutrition as the sole explanation.",
   "A redução de gordura ginoide associada à celíaca no NHANES persistiu em mulheres com sobrepeso/obesidade (-8,7% geral, p=0,005; -11,3% em obesas, p=0,039), contra magreza/desnutrição como única explicação.",
   "clinical_association", ctx("overweight/obese US women (NHANES)","celiac disease autoimmunity","non-celiac overweight/obese women","gynoid percent fat, BMI-stratified","cross-sectional sensitivity analysis, n=2503 (7 celiac)"),
   "emerging","low",
   [ev("DOI:10.64898/2025.12.01.25341350","supporting","cross_sectional",2503,"high",2025,True,"only 7 celiac cases in stratum; estimates unstable")],
   [{"type":"contextualizes","target_hint":"leanness-bias control"}],
   "Extremely small cell counts; cannot exclude all reverse causation.","DOI:10.64898/2025.12.01.25341350"),
 C("In NHANES women, a DXA-defined lipedema-like phenotype (leg-to-trunk fat ratio >90th percentile) was associated with a favorable immunometabolic profile, including 44.2% lower HOMA-IR (p<0.001) and 7.6% lower neutrophil-to-lymphocyte ratio (p=0.012).",
   "Em mulheres do NHANES, o fenótipo tipo-lipedema por DXA (razão gordura perna/tronco >p90) associou-se a perfil imunometabólico favorável, incluindo HOMA-IR 44,2% menor (p<0,001) e relação neutrófilo-linfócito 7,6% menor (p=0,012).",
   "clinical_association", ctx("US women >=20y (NHANES)","lipedema-like phenotype (LTR >90th pct)","controls (LTR <=90th pct)","HOMA-IR, NLR","cross-sectional, n=283 phenotype / 3550 controls"),
   "emerging","low",
   [ev("DOI:10.64898/2025.12.01.25341350","supporting","cross_sectional",3833,"moderate",2025,True,"exploratory; DXA proxy may capture gynoid obesity")],
   [{"type":"associates","target_hint":"peripheral fat as metabolic sink"}],
   "Phenotype proxy unvalidated against clinical lipedema; possible misclassification; no causal direction.","DOI:10.64898/2025.12.01.25341350"),
 C("In NHANES women aged 20-59, a lipedema-like peripheral fat distribution was inversely associated with cancer prevalence: each 1-SD increase in leg-to-trunk fat ratio was associated with 20% lower adjusted odds of cancer (OR 0.795; 95%CI 0.666-0.948; p=0.011).",
   "Em mulheres do NHANES de 20-59 anos, a distribuição periférica de gordura tipo-lipedema associou-se inversamente à prevalência de câncer: cada +1-DP na razão perna/tronco associou-se a chance ajustada de câncer 20% menor (OR 0,795; IC95% 0,666-0,948; p=0,011).",
   "epidemiologic", ctx("US women 20-59 (NHANES)","leg-to-trunk fat ratio (per 1-SD)","lower LTR (more central fat)","self-reported cancer prevalence","cross-sectional, n=2818 (130 cancer)"),
   "emerging","low",
   [ev("DOI:10.64898/2025.12.02.25341445","supporting","cross_sectional",2818,"moderate",2025,True,"prevalence/survivorship not incidence; reverse causation possible; E-value 1.83")],
   [{"type":"associates","target_hint":"peripheral adiposity and lower cancer prevalence"}],
   "Cross-sectional prevalence not incidence; self-reported; residual confounding; cannot distinguish clinical lipedema from peripheral obesity.","DOI:10.64898/2025.12.02.25341445"),
 C("The inverse association between lipedema-like peripheral fat distribution and cancer prevalence was most robust in women without obesity (OR 0.67 per 1-SD LTR; 95%CI 0.53-0.85; p=0.0007).",
   "A associação inversa entre distribuição periférica tipo-lipedema e prevalência de câncer foi mais robusta em mulheres sem obesidade (OR 0,67 por 1-DP de LTR; IC95% 0,53-0,85; p=0,0007).",
   "epidemiologic", ctx("US women 20-59 stratified by obesity (NHANES)","leg-to-trunk fat ratio (per 1-SD)","lower LTR within obesity stratum","cancer prevalence","cross-sectional subgroup, n=2818"),
   "emerging","low",
   [ev("DOI:10.64898/2025.12.02.25341445","supporting","cross_sectional",2818,"moderate",2025,True,"interaction by obesity NS (p=0.58); E-value 2.34 non-obese")],
   [{"type":"associates","target_hint":"peripheral fat protection in non-obese women"}],
   "Underpowered obesity subgroup; survivorship bias; no incidence data.","DOI:10.64898/2025.12.02.25341445"),
 # --- Treatment ---
 C("In women with lipedema, liposuction (tumescent/large-volume) produces significant post-operative reductions in spontaneous pain, edema, bruising, mobility impairment and quality-of-life impairment versus pre-operative status.",
   "Em mulheres com lipedema, a lipoaspiração (tumescente/grande volume) produz reduções pós-operatórias significativas de dor, edema, equimoses, mobilidade e prejuízo de qualidade de vida versus o estado pré-operatório.",
   "therapeutic", ctx("adult women with lipedema (mostly DE/AT cohorts)","liposuction (tumescent and large-volume)","pre-operative baseline (within-subject)","pain, edema, bruising, mobility, QoL","pooled before-after surgical series"),
   "probable","moderate",
   [ev("DOI:10.7759/cureus.55260","supporting","meta_analysis",451,"moderate",2024,True,"7 studies; pooled MD pain 3.41, all p<0.00001; high heterogeneity; before-after data")],
   [{"type":"treats","target_hint":"lipedema symptoms"}],
   "No randomized/controlled comparison; uncontrolled self-reported before-after series; durability uncertain.","DOI:10.7759/cureus.55260"),
 C("Liposuction is not a definitive cure for lipedema: roughly half of patients (~51%) still require ongoing conservative (decongestive) therapy after surgery, supporting its role as an adjunct rather than first-line monotherapy.",
   "A lipoaspiração não é cura definitiva: cerca de metade (~51%) ainda necessita de terapia conservadora após a cirurgia, apoiando seu papel como adjuvante e não monoterapia de primeira linha.",
   "prognostic", ctx("women with lipedema undergoing liposuction","liposuction","expectation of definitive cure","continued need for post-operative conservative therapy","post-surgical care requirement"),
   "probable","moderate",
   [ev("DOI:10.7759/cureus.55260","supporting","meta_analysis",None,"moderate",2024,True,"~51% continued conservative treatment post-surgery (4 studies)")],
   [{"type":"treats","target_hint":"lipedema (partial, combined approach)"}],
   "Definitions of 'need' varied; no controlled long-term follow-up.","DOI:10.7759/cureus.55260"),
 C("Liposuction for lipedema by an experienced team is a safe procedure with a low rate of major complications (no DVT, PE, necrosis or severe anemia observed; minor complications ~1%), though seroma occurs in ~18%.",
   "A lipoaspiração para lipedema por equipe experiente é segura, com baixa taxa de complicações maiores (sem TVP, EP, necrose ou anemia grave; complicações menores ~1%), embora seroma ocorra em ~18%.",
   "therapeutic", ctx("93 women undergoing liposuction (Brazil, 2019-2024)","tumescent liposuction (± adjuncts)","none (descriptive complication rates)","postoperative complications","surgical safety, single experienced team"),
   "emerging","low",
   [ev("DOI:10.1007/s00266-026-05774-7","supporting","cohort",93,"moderate",2026,True,"retrospective; 1 infection + 1 hematoma (1.07%); seroma 18.3%; no major AE")],
   [{"type":"treats","target_hint":"lipedema (surgical safety)"}],
   "Retrospective single-center/single-team; generalizability to less experienced settings unproven.","DOI:10.1007/s00266-026-05774-7"),
 C("In lipedema liposuction, higher relative aspirated fat volume (per 1% body weight) and concomitant minor surgical procedures are independent risk factors for postoperative seroma.",
   "Na lipoaspiração do lipedema, maior volume aspirado relativo (por 1% do peso) e procedimentos cirúrgicos menores concomitantes são fatores de risco independentes para seroma pós-operatório.",
   "causal", ctx("93 women undergoing liposuction for lipedema","high relative aspirated volume; concomitant procedures","lower volume / no concomitant procedures","postoperative seroma","risk factors, multivariable regression"),
   "emerging","low",
   [ev("DOI:10.1007/s00266-026-05774-7","supporting","cohort",93,"moderate",2026,True,"OR volume% 1.58 (1.02-2.43); concomitant procedures 6.77 (1.70-26.97); stage 3.57")],
   [{"type":"causes","target_hint":"postoperative seroma"}],
   "Single-center retrospective; wide CIs; needs prospective validation.","DOI:10.1007/s00266-026-05774-7"),
 C("Ultrasound-assisted liposuction may reduce postoperative seroma risk in lipedema surgery (0 seromas among ultrasound-assisted cases vs 18.4% otherwise), although this finding is hypothesis-generating only.",
   "A lipoaspiração assistida por ultrassom pode reduzir o risco de seroma na cirurgia do lipedema (0 seromas nos casos assistidos vs 18,4%), embora seja achado apenas gerador de hipótese.",
   "therapeutic", ctx("women undergoing liposuction for lipedema","ultrasound-assisted liposuction","non-ultrasound liposuction","postoperative seroma","potential protective effect of an adjunct"),
   "speculative","very_low",
   [ev("DOI:10.1007/s00266-026-05774-7","supporting","cohort",93,"high",2026,True,"0/14 vs 17/76 (p=0.065 NS); zero-event, author-labeled hypothesis-generating")],
   [{"type":"treats","target_hint":"seroma prevention"}],
   "Small subgroup (n=14); zero-event problem; not statistically significant; needs controlled validation.","DOI:10.1007/s00266-026-05774-7"),
 C("In women with lipedema, a low-carbohydrate high-fat (ketogenic) diet significantly reduces body weight, BMI and waist/hip circumferences over a mean of ~16 weeks.",
   "Em mulheres com lipedema, a dieta low-carb e rica em gordura (cetogênica) reduz significativamente peso, IMC e circunferências de cintura/quadril ao longo de ~16 semanas.",
   "therapeutic", ctx("adult women with lipedema (PL/NO/IT cohorts)","low-carbohydrate high-fat / ketogenic diet","pre-intervention baseline","body weight, BMI, waist/hip circumference","anthropometric outcomes, pooled dietary studies"),
   "probable","moderate",
   [ev("DOI:10.3390/nu16193276","supporting","meta_analysis",329,"moderate",2024,True,"7 studies; MD weight 7.94, BMI 4.23, all p<0.0001; mean 15.85 weeks")],
   [{"type":"treats","target_hint":"body composition / weight"}],
   "Few studies, modest N, no long-term follow-up; lipedema-specific fat vs general weight loss not isolated.","DOI:10.3390/nu16193276"),
 C("In women with lipedema, a ketogenic (low-carbohydrate, high-fat) diet produces a small but statistically significant reduction in pain sensitivity.",
   "Em mulheres com lipedema, a dieta cetogênica produz redução pequena, porém estatisticamente significativa, da sensibilidade dolorosa.",
   "therapeutic", ctx("adult women with lipedema","ketogenic / LCHF diet","pre-intervention baseline","pain sensitivity","symptomatic pain outcome"),
   "emerging","low",
   [ev("DOI:10.3390/nu16193276","supporting","meta_analysis",329,"moderate",2024,True,"pooled pain MD 1.12 (0.44-1.79), p=0.001; fewer studies reported pain")],
   [{"type":"treats","target_hint":"lipedema pain"}],
   "Heterogeneous self-report pain scales; causal separation from weight loss unproven.","DOI:10.3390/nu16193276"),
 C("Non-surgical management of lipedema (anti-inflammatory diet, manual lymphatic drainage, aquatic exercise, antioxidant phytotherapeutics) can improve symptoms and reduce limb volume across disease stages in selected patients.",
   "O manejo não cirúrgico do lipedema (dieta anti-inflamatória, drenagem linfática manual, exercício aquático, fitoterápicos antioxidantes) pode melhorar sintomas e reduzir volume em diferentes estágios em pacientes selecionadas.",
   "therapeutic", ctx("women with lipedema (stages 1-4), 5 cases","conservative non-surgical therapy","pre-treatment baseline","symptom score (QuASiL) and limb volume","selected cases, no comparator"),
   "emerging","low",
   [ev("DOI:10.12659/AJCR.934406","supporting","case_series",5,"high",2021,True,"QuASiL improvements and volume losses; uncontrolled, multiple co-interventions")],
   [{"type":"treats","target_hint":"lipedema (conservative)"}],
   "Only 5 selected cases, no control, co-interventions preclude attribution, no durability data.","DOI:10.12659/AJCR.934406"),
 C("An individualized, multidisciplinary approach combining conservative anti-inflammatory therapy with staged liposuction (rather than liposuction as a sole cure) is proposed as the optimal treatment model for lipedema.",
   "Uma abordagem individualizada e multidisciplinar combinando terapia conservadora anti-inflamatória com lipoaspiração escalonada (e não a lipoaspiração como cura isolada) é proposta como modelo de tratamento ideal para o lipedema.",
   "therapeutic", ctx("patients with lipedema across stages","integrated stepwise conservative + staged liposuction","single liposuction as sole/first-line cure","individualized symptom control and function","treatment-strategy recommendation"),
   "emerging","low",
   [ev("DOI:10.7759/cureus.55260","supporting","meta_analysis",451,"moderate",2024,True,"~51% still need conservative therapy → adjunct within comprehensive care"),
    ev("DOI:10.12659/AJCR.934406","supporting","case_series",5,"high",2021,True,"liposuction one tool among several; individualized objectives")],
   [{"type":"treats","target_hint":"integrated multidisciplinary care"}],
   "Synthesized from low-level evidence + expert opinion; no head-to-head trial of staged vs single-session.","DOI:10.7759/cureus.55260"),
 C("In women with lipedema, hormonal contraceptive use is associated with self-reported symptom worsening (58.8% of users; 15.1% reporting symptom onset coinciding with contraceptive initiation).",
   "Em mulheres com lipedema, o uso de anticoncepcionais hormonais associa-se a piora autorrelatada dos sintomas (58,8% das usuárias; 15,1% com início dos sintomas coincidindo com o início do contraceptivo).",
   "clinical_association", ctx("637 Brazilian women, suspected/confirmed lipedema","hormonal contraceptive use","no worsening / non-users","self-reported symptom worsening","observational self-report, Brazil"),
   "probable","moderate",
   [ev("DOI:10.7759/cureus.99189","supporting","cross_sectional",637,"moderate",2025,True,"chi2=213.71 p<0.001; baseline symptom burden strongest predictor; recall/selection bias")],
   [{"type":"associates","target_hint":"estrogenic trigger"}],
   "Self-reported, cross-sectional, social-media-recruited; recall bias; no objective measures.","DOI:10.7759/cureus.99189"),
 C("There is no scientific evidence supporting gestrinone for lipedema: a PRISMA systematic review identified zero clinical trials, observational studies or case reports evaluating it, particularly as subcutaneous implants.",
   "Não há evidência científica que apoie a gestrinona para lipedema: uma revisão sistemática PRISMA não identificou nenhum ensaio, estudo observacional ou relato de caso, particularmente em implantes subcutâneos.",
   "therapeutic", ctx("patients with lipedema","gestrinone (off-label, incl. subcutaneous implants)","evidence-based conservative care","no eligible evidence of efficacy/safety","systematic review to July 2025"),
   "established","moderate",
   [ev("DOI:10.7759/cureus.97213","contradicting","systematic_review",0,"low",2025,True,"zero eligible studies; SBEM and Brazilian Lipedema Association oppose use")],
   [{"type":"contextualizes","target_hint":"hormonal therapy"}],
   "Absence of evidence (no studies) rather than demonstrated lack of effect; implant pharmacokinetics/safety never studied.","DOI:10.7759/cureus.97213"),
 # --- Pathophysiology: empirical observations (NOT the IIT2 theory) ---
 C("Lipedema-affected gluteofemoral adipose tissue shows elevated tissue histamine (~2.2-fold vs controls) in a preliminary metabolomic study.",
   "O tecido adiposo gluteofemoral acometido pelo lipedema mostra histamina tecidual elevada (~2,2 vezes vs controles) em estudo metabolômico preliminar.",
   "clinical_association", ctx("patients with lipedema","lipedema-affected gfWAT","non-lipedema control adipose tissue","elevated tissue histamine (~2.2x)","gluteofemoral adipose tissue"),
   "emerging","low",
   [ev("DOI:10.7417/CT.2023.2496","supporting","basic_science",None,"high",2023,False,"Bonetti et al.; preliminary metabolomics; needs replication")],
   [{"type":"associates","target_hint":"mast cell / histamine activity"}],
   "Preliminary finding needing independent replication with quantitative assays and matched controls.","DOI:10.7417/CT.2023.2496"),
 C("Lipedema gluteofemoral adipose tissue displays a dominant M2 macrophage transcriptomic signature with CD163+ macrophage enrichment (2.58-fold by qPCR; 1171 differentially expressed genes), indicating a type-2 immune microenvironment.",
   "O tecido adiposo gluteofemoral do lipedema exibe assinatura transcriptômica dominante de macrófagos M2 com enriquecimento de CD163+ (2,58 vezes por qPCR; 1171 genes diferencialmente expressos), indicando microambiente imune tipo 2.",
   "clinical_association", ctx("patients with lipedema","lipedema gfWAT","control / abdominal subcutaneous fat / lymphedema","M2/CD163+ macrophage enrichment","gluteofemoral adipose tissue"),
   "probable","moderate",
   [ev("DOI:10.3389/fimmu.2022.1004609","supporting","basic_science",None,"moderate",2022,False,"Wolf et al.; CyTOF + RNA-seq; in vitro functional causality (IPI-549)")],
   [{"type":"associates","target_hint":"type-2 immune polarization"}],
   "Cellular source of IL-4/IL-13 not directly identified; mast-cell- vs hypoxia-driven not resolved.","DOI:10.3389/fimmu.2022.1004609"),
 C("Lipedema has a distinctive quantitative sensory testing (QST) signature in the affected limb — isolated lowered pressure pain threshold and raised vibration detection threshold with spared thermal thresholds — yielding high diagnostic accuracy (PVTH-score AUC 0.958).",
   "O lipedema tem assinatura distintiva de teste sensorial quantitativo (QST) no membro acometido — limiar de dor à pressão reduzido e limiar de detecção vibratória elevado isolados, com limiares térmicos preservados — com alta acurácia diagnóstica (PVTH-score AUC 0,958).",
   "diagnostic", ctx("non-obese women with lipedema","DFNS quantitative sensory testing","unaffected site / controls","selective QST abnormality (PPT-down, VDT-up)","peripheral sensory phenotype, affected limb"),
   "emerging","low",
   [ev("DOI:10.1097/PR9.0000000000001155","supporting","cross_sectional",None,"moderate",2024,False,"Dinnendahl/Bertsch; only PPT-down and VDT-up of 13 parameters; pattern in thigh, absent in hand")],
   [{"type":"associates","target_hint":"lipedema pain phenotype"}],
   "Single study; mechanism of the pattern not established; needs independent replication.","DOI:10.1097/PR9.0000000000001155"),
 # --- Consensus (Brazilian Delphi Consensus Statement on Lipedema, 2025) ---
 C("Lipedema is defined by a disproportionate, symmetrical accumulation of subcutaneous adipose tissue in the limbs relative to the trunk that is characteristically resistant to conventional weight-loss methods (diet and exercise), distinguishing it from common obesity.",
   "O lipedema define-se por acúmulo desproporcional e simétrico de tecido adiposo subcutâneo nos membros em relação ao tronco, caracteristicamente resistente a métodos convencionais de perda de peso (dieta e exercício), distinguindo-o da obesidade comum.",
   "definitional", ctx("adults with lipedema","","common obesity","disproportionate, weight-loss-resistant limb fat","disease definition (Brazilian consensus)"),
   "established","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"Brazilian Delphi consensus; agreement 4.29 (disproportion) and 4.51 (differentiation/weight-loss resistance); level B/C — expert agreement, not primary evidence")],
   [{"type":"contextualizes","target_hint":"obesity differential"}],
   "Consensus-level statement (level B/C); the weight-loss resistance is clinically observed, not quantified in controlled trials.","DOI:10.1590/1677-5449.202301832"),
 C("Patients with lipedema frequently report swelling and a sensation of heaviness in the affected limbs.",
   "Pacientes com lipedema frequentemente relatam inchaço e sensação de peso nos membros acometidos.",
   "clinical_association", ctx("patients with lipedema","lipedema","","swelling and heaviness symptoms","clinical characteristics (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus agreement 4.40, level B")],
   [{"type":"associates","target_hint":"limb heaviness/swelling symptom"}],
   "Symptom endorsed by expert consensus; not quantified against controls.","DOI:10.1590/1677-5449.202301832"),
 C("Several findings suggest a hereditary predisposition to lipedema, with frequent family history among affected women.",
   "Vários achados sugerem predisposição hereditária ao lipedema, com história familiar frequente entre as mulheres acometidas.",
   "causal", ctx("women with lipedema","family history / genetic predisposition","","hereditary predisposition","etiology (consensus)"),
   "emerging","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus agreement 4.26, level B; 'lipedema is hereditary'")],
   [{"type":"associates","target_hint":"genetic/hereditary predisposition"}],
   "Specific genes and inheritance pattern not established; based on family history and expert consensus.","DOI:10.1590/1677-5449.202301832"),
 C("Lipedema can negatively impact mental health and quality of life, and delayed diagnosis or late treatment worsens symptom burden and psychological well-being.",
   "O lipedema pode impactar negativamente a saúde mental e a qualidade de vida, e o diagnóstico ou tratamento tardio agrava a carga de sintomas e o bem-estar psicológico.",
   "clinical_association", ctx("patients with lipedema","lipedema (and diagnostic delay)","","mental health and quality of life","social/psychological aspects (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus agreement 4.66 (mental health/QoL impact) and 4.45 (delayed diagnosis worsens burden), level B/C")],
   [{"type":"associates","target_hint":"mental health / quality of life"}],
   "Psychosocial impact endorsed by consensus; not measured with validated instruments in this statement.","DOI:10.1590/1677-5449.202301832"),
 C("The diagnosis of lipedema is primarily clinical, relying on the patient's medical history, physical examination, and exclusion of differential diagnoses (notably obesity and lymphedema).",
   "O diagnóstico do lipedema é primariamente clínico, baseado na história, no exame físico e na exclusão de diagnósticos diferenciais (notadamente obesidade e linfedema).",
   "diagnostic", ctx("patients with suspected lipedema","clinical assessment (history + exam)","obesity and lymphedema","clinical diagnosis","diagnostic approach (consensus)"),
   "established","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus agreement 4.44, level B; diagnosis relies on history, exam, exclusion of differentials")],
   [{"type":"contextualizes","target_hint":"clinical diagnosis vs imaging"}],
   "No validated objective gold-standard test; diagnosis remains clinical and operator-dependent.","DOI:10.1590/1677-5449.202301832"),
 C("Comprehensive management of lipedema requires a multidisciplinary team (e.g., vascular surgery, endocrinology, orthopedics, plastic surgery, physiotherapy, nutrition, psychiatry/psychology and gynecology) addressing both physical and mental health.",
   "O manejo abrangente do lipedema requer equipe multidisciplinar (ex.: cirurgia vascular, endocrinologia, ortopedia, cirurgia plástica, fisioterapia, nutrição, psiquiatria/psicologia e ginecologia), abordando saúde física e mental.",
   "therapeutic", ctx("patients with lipedema","multidisciplinary team care","single-specialty management","comprehensive management","care model (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus agreement 4.48 (multidisciplinary care essential) and 4.66 (complex disease requiring multidisciplinary treatment), level B")],
   [{"type":"treats","target_hint":"multidisciplinary management"}],
   "Care-model recommendation from expert consensus; not validated against single-specialty management in a trial.","DOI:10.1590/1677-5449.202301832"),
 C("Conservative management (lifestyle and dietary changes, compression therapy, low-impact exercise) is first-line for lipedema, and surgery (liposuction) should be considered only after about one year of clinical treatment, prioritizing mobility and symptom relief over aesthetic outcomes.",
   "O manejo conservador (mudanças de estilo de vida e dieta, compressão, exercício de baixo impacto) é a primeira linha para o lipedema, e a cirurgia (lipoaspiração) deve ser considerada apenas após cerca de um ano de tratamento clínico, priorizando mobilidade e alívio de sintomas sobre resultados estéticos.",
   "therapeutic", ctx("patients with lipedema","conservative first-line care; staged surgical indication","immediate/first-line surgery or aesthetic-driven surgery","treatment sequencing and surgical indication","management recommendation (consensus)"),
   "probable","low",
   [ev("DOI:10.1590/1677-5449.202301832","supporting","consensus",113,"moderate",2025,True,"consensus: conservative management first-line 4.52; surgery only after ~1y clinical treatment 4.46; prioritize mobility/symptom relief over aesthetics 4.09; level B/C")],
   [{"type":"treats","target_hint":"treatment sequencing (conservative-first)"}],
   "Sequencing/indication is expert-consensus guidance, not derived from a controlled comparison of timing strategies.","DOI:10.1590/1677-5449.202301832"),
]

# ---------------- HELD OUT: IIT2 / gfWAT theory (NOT in registry yet) ----------------
held = [
 {"topic":"gfWAT-IIT2 unifying framework","reason":"founder's own theory (preprint, hypothesis)","ref":"DOI:10.20944/preprints202605.1114.v1"},
 {"topic":"Histaminergic peripheral sensitization as mechanism of the lipedema QST triad","reason":"theory mechanism (empirical QST pattern kept separately as SCR-LIP claim)","ref":"DOI:10.20944/preprints202605.1114.v1"},
 {"topic":"Estrogen acting on gfWAT mast-cell estrogen receptors triggering degranulation","reason":"theory mechanism (ER profile of adipose mast cells never characterized)","ref":"DOI:10.20944/preprints202605.1114.v1"},
 {"topic":"Asymmetric lipedema as a natural controlled experiment of local triggers","reason":"theory / open prediction","ref":"DOI:10.20944/preprints202605.1114.v1"},
 {"topic":"Fibromyalgia as a central-sensitization stage of the same mast-cell cascade","reason":"theory subtyping prediction","ref":"DOI:10.20944/preprints202605.1114.v1"},
 {"topic":"Integrative 4-mechanism (inflammatory/hypoxic-hemorrhagic/adipomyofascial/neuromolecular) model of lipedema pain","reason":"mechanistic synthesis tied to the theory","ref":"DOI:10.4236/jbise.2026.193011"},
 {"topic":"Immunological shield: gfWAT as systemic immunoregulatory organ suppressing Th1 (celiac/cancer protection mechanism)","reason":"founder's mechanistic hypothesis (empirical celiac/cancer/HLA/IgG associations kept as SCR-LIP claims)","ref":"DOI:10.7759/cureus.104222"},
 {"topic":"Maternal HLA-DQ2/DQ8 + gluten causing fetal congenital cardiac septal defect","reason":"speculative unpublished hypothesis","ref":"lipedema_HLA_gluten_cardiopatia_fetal.md"},
 {"topic":"hEDS/hypermobility as a shared mast-cell/IIT2 mechanism with lipedema","reason":"theory mechanism (empirical hypermobility comorbidity kept as SCR-LIP claim)","ref":"lipedema_eds_hipermobilidade_IIT2.md"},
 {"topic":"Hashimoto thyroiditis as an organ-specific gluten/HLA IIT2 manifestation","reason":"theory mechanism (empirical thyroid comorbidity kept as SCR-LIP claim)","ref":"lipedema_hashimoto_IIT2.md"},
 {"topic":"Autism/ADHD in male relatives via absent gfWAT 'immune shield'","reason":"speculative theory extension","ref":"lipedema_autismo_neuroinflam_IIT2.md"},
 {"topic":"Mast-cell stabilizers (cromolyn/ketotifen) as disease-modifying therapy for lipedema","reason":"theory-derived therapeutic rationale (no RCT)","ref":"lipedema_iit2_guia_terapias.md"},
 {"topic":"Sarcopenic-valgus / chondromalacia cascade as a downstream consequence","reason":"founder's musculoskeletal hypothesis (editorial)","ref":"DOI:10.7759/cureus.95299"},
]

# assign IDs + metadata
for i, c in enumerate(claims, 1):
    c["id"] = f"SCR-LIP-{i:06d}"
    c.update(COMMON)
# reorder id first
ordered = [{**{"id": c["id"]}, **{k: v for k, v in c.items() if k != "id"}} for c in claims]

with open(os.path.join(DIR, "claims.json"), "w") as f:
    json.dump({"registry":"SCR-LIP","version":"0.1","date":"2026-05-30","count":len(ordered),"claims":ordered}, f, ensure_ascii=False, indent=2)

with open(os.path.join(DIR, "_held_out_theory.json"), "w") as f:
    json.dump({"note":"Author's IIT2/gfWAT theory — intentionally NOT in the registry yet (per author, 2026-05-30). Staged for future inclusion once empirically supported.","count":len(held),"items":held}, f, ensure_ascii=False, indent=2)

# CSV (flattened)
with open(os.path.join(DIR, "claims.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["id","claim_type","knowledge_state","evidence_confidence","statement","primary_amato_source","n_evidence","amato_evidence","gaps"])
    for c in ordered:
        amato_n = sum(1 for e in c["evidence"] if e.get("amato_authored"))
        w.writerow([c["id"], c["claim_type"], c["knowledge_state"], c["evidence_confidence"], c["statement"],
                    c["primary_amato_source"], len(c["evidence"]), amato_n, c["gaps"]])

print(f"Registry claims: {len(ordered)}")
print(f"Held-out theory items: {len(held)}")
from collections import Counter
print("by knowledge_state:", dict(Counter(c["knowledge_state"] for c in ordered)))
print("by claim_type:", dict(Counter(c["claim_type"] for c in ordered)))
print("claims with >=1 Amato-authored evidence:", sum(1 for c in ordered if any(e.get("amato_authored") for e in c["evidence"])))
